#!/bin/sh
alias aliases='nvim ~/.aliases.sh'
alias c='clear'
alias e='exit'
alias gp='cd "$(cat ~/.config/current_project)"'
alias l='exa -l'
alias lh='exa -l -a'
alias ls='exa -l'
alias reload='unalias -a && . "$HOME"/.aliases.sh'
alias rimraf='rm -rf'
alias sc='pwd > ~/.config/current_project'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias vimrc='vim ~/.config/nvim/init.lua'
alias zshrc='nvim ~/.zshrc'
alias zshrc='vim ~/.zshrc'
